[tool.ruff]
# Ajustes generales (compartidos por linter y formateador)
line-length = 88
target-version = "py310"

[tool.lint]
# Selección de reglas
# E, F: Pyflakes y errores de Pycodestyle
# B: Bugbear (errores comunes)
# I: Isort (orden de imports)
# UP: Pyupgrade (actualiza sintaxis a Python 3.10+)
# COM812: Trailing comma missing
select = ["E", "F", "B", "I", "UP", "COM812",]
ignore = ["E501"] # Ignora líneas largas (el formateador se encarga)

[tool.lint.isort]
known-first-party = ["sync"] # Nombre del modulo
force-single-line = false
split-on-trailing-comma = true

[tool.format]
# Ruff-format usa por defecto 88 caracteres y comillas dobles,
# igual que Black, así que no suele hacer falta configurar nada más.
quote-style = "double"
indent-style = "space"
# Asegúrate de que esto esté en false (es el valor por defecto)
skip-magic-trailing-comma = false